{{- if .Values.volumes }}
{{- range $name, $volume := .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mule.fullname" $ }}-{{ $name }}-pvc
  labels:
    {{- include "mule.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ $volume.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ $volume.storageClassName }}
  resources:
    requests:
      storage: {{ $volume.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mule.fullname" $ }}-{{ $name }}-pv
  labels:
    {{- include "mule.labels" $ | nindent 4 }}
spec:
  storageClassName: {{ $volume.storageClassName }}
  capacity:
    storage: {{ $volume.size }}
  accessModes:
    - {{ $volume.accessMode | default "ReadWriteOnce" }}
  hostPath:
    path: {{ $volume.mountPath }}
{{- end }}
{{- end }}