apiVersion: v1
kind: Service
metadata:
  name: {{ include "mule.fullname" . }}
  labels:
    {{- include "mule.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9001
      targetPort: http
      protocol: TCP
      name: managment
  selector:
    {{- include "mule.selectorLabels" . | nindent 4 }}
