name: Docker Image CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      tag:  "2024.6.1-main"
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Install Moon
      uses: 'moonrepo/setup-toolchain@v0'
    - run: 'moon run client:docker-build'
    - run: 'moon run server:docker-build'
