name: Docker Image CI

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      tag: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Install Moon
      uses: 'moonrepo/setup-toolchain@v0'
    - run: 'moon ci'
